### ISSUE TITLE
New irispie version fails to solve a model that worked with previous versions

### ISSUE THREAD

**Issue by tmotl2** [IRIS-Solutions-Team/irispie#13]
Files worked with irispie-0.54.8, crash with irispie-0.56.4.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /home/tmotl/Git/OGR/morocco-macro-fiscal-model/modeling/morfis/create_model.py:3
      1 # Load packages
----> 3 import irispie as ir
      4 import sys
      5 import os

File ~/Git/OGR/morocco-macro-fiscal-model/.venv/lib/python3.12/site-packages/irispie/__init__.py:4
      2 import importlib.metadata as _md
----> 4 from .dates import *
      5 from .dates import __all__ as dates_all
      7 from .series import *

File ~/Git/OGR/morocco-macro-fiscal-model/.venv/lib/python3.12/site-packages/irispie/dates.py:418
    403     return wrapper
    404     #]
    408 @_dm.reference(
    409     path=("data_management", "periods.md", ),
    410     categories={
    411         "constructor": "Creating new time periods",
    412         "arithmetics_comparison": "Adding, subtracting, and comparing time periods",
    413         "refrequency": "Converting time periods to different frequencies",
    414         "conversion": "Converting time periods to different representations",
    415         "print": "Converting time periods to strings",
...
   1096     def resolve(self, context: ResolutionContextProtocol) -> Self:
   1097         return self
   1099     def __bool__(self) -> bool:

AttributeError: module 'documark' has no attribute 'no_reference'
